services:
  - type: web
    name: grocery-management-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    autoDeploy: true  # Enables auto-deploy on GitHub pushes
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grocery-db  # The name you give your PostgreSQL database (see below)
          property: connectionString
    regions:
      - oregon

  - type: postgres
    name: grocery-db
    plan: free
